---

- name: Generate default paramaters
  include_vars:
    file: files/default_parameters.yml
    name: default_parameters

- name: Apply replicator configuration
  uri:
    url: "{{ api_endpoint }}/connectors/{{ item.name }}/config"
    method: PUT
    url_username: admin
    url_password: "{{ rest_api_password }}"
    force_basic_auth: true
    body_format: json
    body: "{{ default_parameters | combine(other_default_parameters) | combine(replicator_config) }}"
    status_code:
      - 200
      - 201
  vars:
    replicator_config: "{{ item | dict2items | selectattr('key', 'ne', 'name') | list | items2dict }}"
    other_default_parameters:
      dest.kafka.client.id: "client-{{ item.name }}"
      src.kafka.client.id: "client-{{ item.name }}"
      src.consumer.group.id: "consumer-{{ item.name }}"
