---

- name: Ensures /tmp/splunkapp exists 
  file: path=/tmp/splunkapp state=directory

- name: copy app
  copy:
    src="/tmp/splunk-add-on-for-microsoft-windows_820.tgz"
    dest="/tmp/splunkapp/splunk-add-on-for-microsoft-windows_820.tgz"

- name: Load binary file into variable             
  local_action:                               
    module: slurp                             
    src: "/tmp/splunkapp/splunk-add-on-for-microsoft-windows_820.tgz"     
  register: bin_file

- name: get list configuration
  uri:
    url: "{{ api_endpoint }}/services/apps/local"
    method: POST
    url_username: splunkadmin
    url_password: splunk$#20
    body: {{ lookup('file', '{{ bin_file.contet }}') | b64encode }}
#      file1:
#        filename: /tmp/splunkapp/splunk-add-on-for-microsoft-windows_820.tgz
#        mime_type: application/octet-stream
    force_basic_auth: true
    validate_certs: no
    body_format: form-urlencoded
  register: post_responses
    
- name: Display responses
  debug:
    var: post_responses
