---

- name: Ensures /tmp/splunkapp exists 
  file: path=/tmp/splunkapp state=directory
  delegate_to: 20.93.115.65

- name: copy app to splunk server
  copy:
    src="/tmp/splunk-add-on-for-microsoft-windows_820.tgz"
    dest="/tmp/splunkapp/splunk-add-on-for-microsoft-windows_820.tgz"

- name: push app
  command: curl -k -u {{ rest_api_user }}:'{{ rest_api_password }}' -X POST {{ api_endpoint }}/services/apps/local -d 'name=/tmp/splunkapp/splunk-add-on-for-microsoft-windows_820.tgz&filename=True&update=True'
  register: post_responses
  delegate_to: 20.93.115.65
    
- name: Display responses
  debug:
    var: post_responses
  
