---

- name: Ensures /tmp/splunkapp exists 
  file: path=/tmp/splunkapp state=directory

- name: copy app
  copy:
    src="/tmp/splunk-add-on-for-microsoft-windows_820.tgz"
    dest="/tmp/splunkapp/splunk-add-on-for-microsoft-windows_820.tgz"

- name: get list configuration
  uri:
    url: "{{ api_endpoint }}/services/apps/local"
    method: POST
    url_username: admin
    url_password: admin1234
    body:
      file1:
        name: /tmp/splunkapp/splunk-add-on-for-microsoft-windows_820.tgz
        filename: true
        update: true
       mime_type: application/octet-stream
    text_form_field: value
    force_basic_auth: true
    validate_certs: no
    body_format: form-urlencoded
  register: post_responses
    
- name: Display responses
  debug:
    var: post_responses
