---

- name: Ensures /tmp/splunkapp exists 
  file: path=/tmp/splunkapp state=directory

- name: copy app
  copy:
    src="/tmp/splunk-add-on-for-microsoft-windows_820.tgz"
    dest="/tmp/splunkapp/splunk-add-on-for-microsoft-windows_820.tgz"

- name: get list configuration
  uri:
    url: "{{ api_endpoint }}/services/apps/local"
    method: POST
    url_username: splunkadmin
    url_password: splunk$#20
    body:
      file1:
        filename: /tmp/splunkapp/splunk-add-on-for-microsoft-windows_820.tgz
        mime_type: application/octet-stream
      text_form_field: value
    force_basic_auth: true
    validate_certs: no
    body_format: raw
  register: post_responses
    
- name: Display responses
  debug:
    var: post_responses
